name: Run PHPUnit tests
on:
  push:
    branches:
      - main

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Install dependencies
          run: composer install
        - name: Bootstrap application
          run: |
            cp .env.example .env
            php artisan key:generate
        - name: Create SQLite database
          run: touch database/test_database.sqlite
        - name: Run PHPUnit tests
          run: ./vendor/bin/phpunit
